dist: bionic

before_script:
  - rm -rf daemon

jobs:
  include:
    - stage: coin
      name: "Bitcoin Test"
      script:
        - bash install.sh list
        - bash install.sh bitcoind
        - bash bitcoind autoinstall
    - stage: coin
      name: "Litecoin Test"
      script:
        - bash install.sh list
        - bash install.sh litecoind
        - bash litecoind autoinstall